public class ArthimaticCalculations {
    public void addition(integer x, integer y){
       
        integer z=x+y;
        system.debug('addition is '+z);
    }  
    public void subtraction(integer x, integer y){
        
        integer z=x-y;
        system.debug('subtraction is '+z);
    }  
    public void multiplication(integer x,integer y, integer m){
       
        integer z=x*y*m;
        system.debug('multiplication is '+z);
    }
}