public class CheckDatatypes {
    public void methodBoolean(){
        Boolean checkBoolean=true;
        system.debug('checkBloon is=> '+ checkBoolean);
    }
    public void methodInteger(){
        integer varFirst=1;
        integer varSecond=2;
        system.debug('First is '+varFirst+' and Second is '+varSecond);
    }
    public void stringMethod(){
        string varName='Name';
        string var2Name='Elife';
        system.debug(varName+' '+var2Name);
    }
}